spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5433/avia'
    username: 'postgres'
    password: '123'

jpa:
  show-sql: true
#
#  my-config:
#    secret: acIw5hK2aFaS62NE

